name: Watch on Bilibili
on:
  schedule:
    - cron: '30 2,10 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to launch'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config --global user.email "ttlarva@qq.com"
      - run: git config --global user.name "ttlarva"
      - run: python3 ./scripts/watch-bilibili.py
      - run: git commit -a -m "update followers count daily"
      - run: git push
