name: Watch on Bilibili
on:
  schedule:
    - cron: '30 2,10 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: cd scripts
      - run: git config --global user.email "ttlarva@qq.com"
      - run: git config --global user.name "ttlarva"
      - run: python3 watch-bilibili.py
      - run: git commit -a -m "update followers count daily"
